# Generated by Django 5.1 on 2024-08-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
