# Generated by Django 5.1 on 2024-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_orderitem_quantity_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Baking', 'Baking'), ('Baked', 'Baked'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order Received', max_length=100),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
